In [1]:
from peptdeep.pretrained_models import ModelManager
import pandas as pd
from peptdeep.settings import global_settings

model_mgr = ModelManager(mask_modloss=True, device='gpu')

/srv/data1/home/aaron/envs/miniconda3/envs/saenv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
model_mgr.instrument = "timsTOF"
model_mgr.load_installed_models()

In [3]:
from peptdeep import settings

settings.global_settings

{'model': {'frag_types': ['b', 'y', 'b_modloss', 'y_modloss'],
  'max_frag_charge': 2},
 'PEPTDEEP_HOME': '/home/aaron/peptdeep',
 'local_model_zip_name': 'pretrained_models.zip',
 'model_url': 'https://github.com/MannLabs/alphapeptdeep/releases/download/pre-trained-models/pretrained_models.zip',
 'task_workflow': ['library'],
 'task_choices': ['train', 'library'],
 'thread_num': 16,
 'MAX_THREADS': 60,
 'torch_device': {'device_type': 'gpu',
  'device_type_choices': ['get_available', 'gpu', 'mps', 'cpu'],
  'device_ids': []},
 'log_level': 'info',
 'log_level_choices': ['debug', 'info', 'warning', 'error', 'critical'],
 'common': {'modloss_importance_level': 1.0, 'user_defined_modifications': {}},
 'peak_matching': {'ms2_ppm': True,
  'ms2_tol_value': 20.0,
  'ms1_ppm': True,
  'ms1_tol_value': 20.0},
 'model_mgr': {'default_nce': 30.0,
  'default_instrument': 'Lumos',
  'mask_modloss': True,
  'model_type': 'generic',
  'model_choices': ['generic', 'phos', 'hla', 'digly'],
  'external_ms2_model': '',
  'external_rt_model': '',
  'external_ccs_model': '',
  'charge_model_type': 'seq',
  'charge_model_choices': ['seq', 'modseq'],
  'charge_model_file': '',
  'charge_prob_cutoff': 0.3,
  'use_predicted_charge_in_speclib': True,
  'instrument_group': {'ThermoTOF': 'ThermoTOF',
   'Astral': 'ThermoTOF',
   'Lumos': 'Lumos',
   'QE': 'QE',
   'timsTOF': 'timsTOF',
   'SciexTOF': 'SciexTOF',
   'Fusion': 'Lumos',
   'Eclipse': 'Lumos',
   'Velos': 'Lumos',
   'Elite': 'Lumos',
   'OrbitrapTribrid': 'Lumos',
   'ThermoTribrid': 'Lumos',
   'QE+': 'QE',
   'QEHF': 'QE',
   'QEHFX': 'QE',
   'Exploris': 'QE',
   'Exploris480': 'QE',
   'THERMOTOF': 'ThermoTOF',
   'ASTRAL': 'ThermoTOF',
   'LUMOS': 'Lumos',
   'TIMSTOF': 'timsTOF',
   'SCIEXTOF': 'SciexTOF',
   'FUSION': 'Lumos',
   'ECLIPSE': 'Lumos',
   'VELOS': 'Lumos',
   'ELITE': 'Lumos',
   'ORBITRAPTRIBRID': 'Lumos',
   'THERMOTRIBRID': 'Lumos',
   'EXPLORIS': 'QE',
   'EXPLORIS480': 'QE'},
  'predict': {'batch_size_ms2': 512,
   'batch_size_rt_ccs': 1024,
   'batch_size_charge': 1024,
   'verbose': True,
   'multiprocessing': True},
  'transfer': {'model_output_folder': '/home/aaron/peptdeep/refined_models',
   'epoch_ms2': 20,
   'warmup_epoch_ms2': 10,
   'batch_size_ms2': 512,
   'lr_ms2': 0.0001,
   'epoch_rt_ccs': 40,
   'warmup_epoch_rt_ccs': 10,
   'batch_size_rt_ccs': 1024,
   'lr_rt_ccs': 0.0001,
   'verbose': False,
   'grid_nce_search': False,
   'grid_nce_first': 15.0,
   'grid_nce_last': 45.0,
   'grid_nce_step': 3.0,
   'grid_instrument': ['Lumos'],
   'psm_type': 'alphapept',
   'psm_type_choices': ['alphapept',
    'pfind',
    'maxquant',
    'diann',
    'speclib_tsv',
    'msfragger_pepxml',
    'spectronaut_report'],
   'dda_psm_types': ['alphapept', 'pfind', 'maxquant', 'msfragger_pepxml'],
   'psm_files': [],
   'ms_file_type': 'alphapept_hdf',
   'ms_file_type_choices': ['alphapept_hdf', 'thermo_raw', 'mgf', 'mzml'],
   'ms_files': [],
   'psm_num_to_train_ms2': 100000000,
   'psm_num_per_mod_to_train_ms2': 50,
   'psm_num_to_test_ms2': 0,
   'psm_num_to_train_rt_ccs': 100000000,
   'psm_num_per_mod_to_train_rt_ccs': 50,
   'psm_num_to_test_rt_ccs': 0,
   'top_n_mods_to_train': 10,
   'psm_modification_mapping': {}}},
 'library': {'infile_type': 'fasta',
  'infile_type_choices': ['fasta',
   'sequence_table',
   'peptide_table',
   'precursor_table',
   'all_other_psm_reader_types'],
  'infiles': ['xxx.fasta'],
  'fasta': {'protease': 'trypsin',
   'protease_choices': ['trypsin',
    '([KR])',
    'trypsin_not_P',
    '([KR](?=[^P]))',
    'lys-c',
    'K',
    'lys-n',
    '\\w(?=K)',
    'chymotrypsin',
    'asp-n',
    'glu-c'],
   'max_miss_cleave': 2,
   'add_contaminants': False},
  'fix_mods': ['Carbamidomethyl@C'],
  'var_mods': ['Acetyl@Protein_N-term', 'Oxidation@M'],
  'special_mods': [],
  'special_mods_cannot_modify_pep_n_term': False,
  'special_mods_cannot_modify_pep_c_term': False,
  'labeling_channels': {},
  'min_var_mod_num': 0,
  'max_var_mod_num': 2,
  'min_special_mod_num': 0,
  'max_special_mod_num': 1,
  'min_precursor_charge': 2,
  'max_precursor_charge': 4,
  'min_peptide_len': 7,
  'max_peptide_len': 35,
  'min_precursor_mz': 200.0,
  'max_precursor_mz': 2000.0,
  'decoy': 'None',
  'decoy_choices': ['protein_reverse', 'pseudo_reverse', 'diann', 'None'],
  'max_frag_charge': 2,
  'frag_types': ['b', 'y'],
  'rt_to_irt': False,
  'irt_library': 'xxx/library.tsv',
  'irt_library_type': 'speclib_tsv',
  'generate_precursor_isotope': False,
  'output_folder': '/home/aaron/peptdeep/spec_libs',
  'output_tsv': {'enabled': False,
   'min_fragment_mz': 200.0,
   'max_fragment_mz': 2000.0,
   'min_relative_intensity': 0.001,
   'keep_higest_k_peaks': 12,
   'translate_batch_size': 100000,
   'translate_mod_to_unimod_id': False}}}

In [4]:
human_atlas_library = pd.read_csv(
    "/srv/data1/home/aaron/projects/hatlas/data/results/fragpipie_library_221102/library.tsv",
    sep="\t"
)
human_atlas_library

,PrecursorMz,ProductMz,Annotation,ProteinId,GeneName,PeptideSequence,ModifiedPeptideSequence,PrecursorCharge,LibraryIntensity,NormalizedRetentionTime,PrecursorIonMobility,FragmentType,FragmentCharge,FragmentSeriesNumber,FragmentLossType,AverageExperimentalRetentionTime
0,349.513698,147.112805,y1^1,O75636,FCN3,YAVSEAAAHK,YAVSEAAAHK,3,2526.738037,15.326883,NaN,y,1,1,NaN,1225.024090
1,349.513698,213.626611,y4^2,O75636,FCN3,YAVSEAAAHK,YAVSEAAAHK,3,546.524048,15.326883,NaN,y,2,4,NaN,1225.024090
2,349.513698,235.107720,b2^1,O75636,FCN3,YAVSEAAAHK,YAVSEAAAHK,3,9334.356445,15.326883,NaN,b,1,2,NaN,1225.024090
3,349.513698,284.171717,y2^1,O75636,FCN3,YAVSEAAAHK,YAVSEAAAHK,3,10000.000000,15.326883,NaN,y,1,2,NaN,1225.024090
4,349.513698,334.176134,b3^1,O75636,FCN3,YAVSEAAAHK,YAVSEAAAHK,3,2099.843018,15.326883,NaN,b,1,3,NaN,1225.024090
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7783445,1823.885979,1750.969785,y17^1,P02751,FN1,VEYELSEEGDEPQYLDLPSTATSVNIPDLLPGR,VEYELSEEGDEPQYLDLPSTATSVNIPDLLPGR,2,2078.210938,73.677880,NaN,y,1,17,NaN,5870.420461
7783446,1823.885979,1865.996729,y18^1,P02751,FN1,VEYELSEEGDEPQYLDLPSTATSVNIPDLLPGR,VEYELSEEGDEPQYLDLPSTATSVNIPDLLPGR,2,1195.675781,73.677880,NaN,y,1,18,NaN,5870.420461
7783447,1823.885979,1979.080793,y19^1,P02751,FN1,VEYELSEEGDEPQYLDLPSTATSVNIPDLLPGR,VEYELSEEGDEPQYLDLPSTATSVNIPDLLPGR,2,1067.734009,73.677880,NaN,y,1,19,NaN,5870.420461
7783448,1823.885979,2142.144122,y20^1,P02751,FN1,VEYELSEEGDEPQYLDLPSTATSVNIPDLLPGR,VEYELSEEGDEPQYLDLPSTATSVNIPDLLPGR,2,558.245300,73.677880,NaN,y,1,20,NaN,5870.420461
7783449,1823.885979,2367.255465,y22^1,P02751,FN1,VEYELSEEGDEPQYLDLPSTATSVNIPDLLPGR,VEYELSEEGDEPQYLDLPSTATSVNIPDLLPGR,2,977.769287,73.677880,NaN,y,1,22,NaN,5870.420461

In [5]:
prediction_columns = [
    'PeptideSequence',
    'ModifiedPeptideSequence',
    'PrecursorCharge'
]

In [6]:
precursors = human_atlas_library[prediction_columns].drop_duplicates().reset_index(drop=True)

In [7]:
precursors

,PeptideSequence,ModifiedPeptideSequence,PrecursorCharge
0,YAVSEAAAHK,YAVSEAAAHK,3
1,MFQEIVHK,M(UniMod:35)FQEIVHK,3
2,LHMLELHCESK,LHMLELHC(UniMod:4)ESK,4
3,WETSFNHK,WETSFNHK,3
4,LMNHYINK,LM(UniMod:35)NHYINK,3
...,...,...,...
335400,SFAAGIQALGGTNINDAMLMAVQLLDSSNQEER,SFAAGIQALGGTNINDAMLMAVQLLDSSNQEER,2
335401,ECVGFEAVQEVPVGLVQPASATLYDYYNPER,EC(UniMod:4)VGFEAVQEVPVGLVQPASATLYDYYNPER,2
335402,TFQIPGYTVPVVNVEVSPFTIEMSAFGYVFPK,TFQIPGYTVPVVNVEVSPFTIEM(UniMod:35)SAFGYVFPK,2
335403,CSGTEASVVAPPPVVLLPDVETPSEEDCMFGNGK,C(UniMod:4)SGTEASVVAPPPVVLLPDVETPSEEDC(UniMod:...,2
335404,VEYELSEEGDEPQYLDLPSTATSVNIPDLLPGR,VEYELSEEGDEPQYLDLPSTATSVNIPDLLPGR,2

In [8]:
mod_translation = {
    'UniMod:1': 'Acetyl@Protein N-term',
    'UniMod:4': 'Carbamidomethyl@C',
    'UniMod:35': 'Oxidation@M'
}

In [9]:
precursors

,PeptideSequence,ModifiedPeptideSequence,PrecursorCharge
0,YAVSEAAAHK,YAVSEAAAHK,3
1,MFQEIVHK,M(UniMod:35)FQEIVHK,3
2,LHMLELHCESK,LHMLELHC(UniMod:4)ESK,4
3,WETSFNHK,WETSFNHK,3
4,LMNHYINK,LM(UniMod:35)NHYINK,3
...,...,...,...
335400,SFAAGIQALGGTNINDAMLMAVQLLDSSNQEER,SFAAGIQALGGTNINDAMLMAVQLLDSSNQEER,2
335401,ECVGFEAVQEVPVGLVQPASATLYDYYNPER,EC(UniMod:4)VGFEAVQEVPVGLVQPASATLYDYYNPER,2
335402,TFQIPGYTVPVVNVEVSPFTIEMSAFGYVFPK,TFQIPGYTVPVVNVEVSPFTIEM(UniMod:35)SAFGYVFPK,2
335403,CSGTEASVVAPPPVVLLPDVETPSEEDCMFGNGK,C(UniMod:4)SGTEASVVAPPPVVLLPDVETPSEEDC(UniMod:...,2
335404,VEYELSEEGDEPQYLDLPSTATSVNIPDLLPGR,VEYELSEEGDEPQYLDLPSTATSVNIPDLLPGR,2

In [10]:
precursors['ModifiedPeptideSequence'].str.findall("\(")

0             []
1            [(]
2            [(]
3             []
4            [(]
           ...
335400        []
335401       [(]
335402       [(]
335403    [(, (]
335404        []
Name: ModifiedPeptideSequence, Length: 335405, dtype: object

In [11]:
import re

def id_mod_sites(modified_peptide_sequence):

    tokens = re.split(r"\(UniMod:[0-9]+\)", modified_peptide_sequence)
    mod_site = 0
    mod_sites = []
    for token in tokens[:-1]:

        mod_site += len(token)

        mod_sites.append(str(mod_site))

    if len(mod_sites) > 1:

        return ";".join(mod_sites)
    
    elif len(mod_sites) == 1:

        return mod_sites[0]
    
    else:

        return ""

In [12]:
precursors['mod_sites'] = precursors['ModifiedPeptideSequence'].apply(
    id_mod_sites
)

In [13]:
precursors['mod_sites'] = precursors['mod_sites'].replace(-1, 'NaN')
precursors

,PeptideSequence,ModifiedPeptideSequence,PrecursorCharge,mod_sites
0,YAVSEAAAHK,YAVSEAAAHK,3,
1,MFQEIVHK,M(UniMod:35)FQEIVHK,3,1
2,LHMLELHCESK,LHMLELHC(UniMod:4)ESK,4,8
3,WETSFNHK,WETSFNHK,3,
4,LMNHYINK,LM(UniMod:35)NHYINK,3,2
...,...,...,...,...
335400,SFAAGIQALGGTNINDAMLMAVQLLDSSNQEER,SFAAGIQALGGTNINDAMLMAVQLLDSSNQEER,2,
335401,ECVGFEAVQEVPVGLVQPASATLYDYYNPER,EC(UniMod:4)VGFEAVQEVPVGLVQPASATLYDYYNPER,2,2
335402,TFQIPGYTVPVVNVEVSPFTIEMSAFGYVFPK,TFQIPGYTVPVVNVEVSPFTIEM(UniMod:35)SAFGYVFPK,2,23
335403,CSGTEASVVAPPPVVLLPDVETPSEEDCMFGNGK,C(UniMod:4)SGTEASVVAPPPVVLLPDVETPSEEDC(UniMod:...,2,1;28
335404,VEYELSEEGDEPQYLDLPSTATSVNIPDLLPGR,VEYELSEEGDEPQYLDLPSTATSVNIPDLLPGR,2,

In [14]:
precursors['nAA'] = precursors['PeptideSequence'].str.len()

In [15]:
extracted_mods = precursors['ModifiedPeptideSequence'].str.extractall(r'\((.*?)\)')
extracted_mods

                      0
       match
1      0      UniMod:35
2      0       UniMod:4
4      0      UniMod:35
14     0       UniMod:4
16     0       UniMod:4
...                 ...
335399 1       UniMod:4
335401 0       UniMod:4
335402 0      UniMod:35
335403 0       UniMod:4
       1       UniMod:4

[143494 rows x 1 columns]

In [16]:
extracted_mods = extracted_mods.reset_index()

extracted_mods_idx = dict()

for idx, row in extracted_mods.iterrows():

    mods_ = extracted_mods_idx.get(row['level_0'], [])

    mods_.append(row[0])

    extracted_mods_idx[row['level_0']] = mods_

for key, value in extracted_mods_idx.items():

    if len(value) > 1:

        extracted_mods_idx[key] = ";".join(value)

    elif len(value) == 1:

        extracted_mods_idx[key] = value[0]

    else:

        extracted_mods_idx[key] = ""

In [17]:
mods = pd.DataFrame(
    {
        "mods": extracted_mods_idx.values()
    },
    index=extracted_mods_idx.keys()
)

In [18]:
precursors = precursors.join(
    mods
)

In [19]:
precursors['precursor_id'] = precursors['ModifiedPeptideSequence'] + precursors['PrecursorCharge'].astype(str)

In [20]:
predict_df = precursors[['precursor_id', 'PeptideSequence', 'PrecursorCharge', 'mods', 'mod_sites', 'nAA']].copy()

In [21]:
predict_df = predict_df.rename(
    columns={
        "PeptideSequence": "sequence",
        "PrecursorCharge": "charge"
    }
)
predict_df

,precursor_id,sequence,charge,mods,mod_sites,nAA
0,YAVSEAAAHK3,YAVSEAAAHK,3,NaN,,10
1,M(UniMod:35)FQEIVHK3,MFQEIVHK,3,UniMod:35,1,8
2,LHMLELHC(UniMod:4)ESK4,LHMLELHCESK,4,UniMod:4,8,11
3,WETSFNHK3,WETSFNHK,3,NaN,,8
4,LM(UniMod:35)NHYINK3,LMNHYINK,3,UniMod:35,2,8
...,...,...,...,...,...,...
335400,SFAAGIQALGGTNINDAMLMAVQLLDSSNQEER2,SFAAGIQALGGTNINDAMLMAVQLLDSSNQEER,2,NaN,,33
335401,EC(UniMod:4)VGFEAVQEVPVGLVQPASATLYDYYNPER2,ECVGFEAVQEVPVGLVQPASATLYDYYNPER,2,UniMod:4,2,31
335402,TFQIPGYTVPVVNVEVSPFTIEM(UniMod:35)SAFGYVFPK2,TFQIPGYTVPVVNVEVSPFTIEMSAFGYVFPK,2,UniMod:35,23,32
335403,C(UniMod:4)SGTEASVVAPPPVVLLPDVETPSEEDC(UniMod:...,CSGTEASVVAPPPVVLLPDVETPSEEDCMFGNGK,2,UniMod:4;UniMod:4,1;28,34
335404,VEYELSEEGDEPQYLDLPSTATSVNIPDLLPGR2,VEYELSEEGDEPQYLDLPSTATSVNIPDLLPGR,2,NaN,,33

In [22]:
predict_df = predict_df.fillna("")
predict_df

,precursor_id,sequence,charge,mods,mod_sites,nAA
0,YAVSEAAAHK3,YAVSEAAAHK,3,,,10
1,M(UniMod:35)FQEIVHK3,MFQEIVHK,3,UniMod:35,1,8
2,LHMLELHC(UniMod:4)ESK4,LHMLELHCESK,4,UniMod:4,8,11
3,WETSFNHK3,WETSFNHK,3,,,8
4,LM(UniMod:35)NHYINK3,LMNHYINK,3,UniMod:35,2,8
...,...,...,...,...,...,...
335400,SFAAGIQALGGTNINDAMLMAVQLLDSSNQEER2,SFAAGIQALGGTNINDAMLMAVQLLDSSNQEER,2,,,33
335401,EC(UniMod:4)VGFEAVQEVPVGLVQPASATLYDYYNPER2,ECVGFEAVQEVPVGLVQPASATLYDYYNPER,2,UniMod:4,2,31
335402,TFQIPGYTVPVVNVEVSPFTIEM(UniMod:35)SAFGYVFPK2,TFQIPGYTVPVVNVEVSPFTIEMSAFGYVFPK,2,UniMod:35,23,32
335403,C(UniMod:4)SGTEASVVAPPPVVLLPDVETPSEEDC(UniMod:...,CSGTEASVVAPPPVVLLPDVETPSEEDCMFGNGK,2,UniMod:4;UniMod:4,1;28,34
335404,VEYELSEEGDEPQYLDLPSTATSVNIPDLLPGR2,VEYELSEEGDEPQYLDLPSTATSVNIPDLLPGR,2,,,33

In [23]:
mod_translation = {
    'UniMod:1': 'Acetyl@Protein N-term',
    'UniMod:4': 'Carbamidomethyl@C',
    'UniMod:35': 'Oxidation@M'
}

In [24]:
predict_df['mods'] = predict_df['mods'].str.replace("UniMod:1", "Acetyl@Protein N-term")
predict_df['mods'] = predict_df['mods'].str.replace("UniMod:4", "Carbamidomethyl@C")
predict_df['mods'] = predict_df['mods'].str.replace("UniMod:35", "Oxidation@M")

In [25]:
predict_df

,precursor_id,sequence,charge,mods,mod_sites,nAA
0,YAVSEAAAHK3,YAVSEAAAHK,3,,,10
1,M(UniMod:35)FQEIVHK3,MFQEIVHK,3,Oxidation@M,1,8
2,LHMLELHC(UniMod:4)ESK4,LHMLELHCESK,4,Carbamidomethyl@C,8,11
3,WETSFNHK3,WETSFNHK,3,,,8
4,LM(UniMod:35)NHYINK3,LMNHYINK,3,Oxidation@M,2,8
...,...,...,...,...,...,...
335400,SFAAGIQALGGTNINDAMLMAVQLLDSSNQEER2,SFAAGIQALGGTNINDAMLMAVQLLDSSNQEER,2,,,33
335401,EC(UniMod:4)VGFEAVQEVPVGLVQPASATLYDYYNPER2,ECVGFEAVQEVPVGLVQPASATLYDYYNPER,2,Carbamidomethyl@C,2,31
335402,TFQIPGYTVPVVNVEVSPFTIEM(UniMod:35)SAFGYVFPK2,TFQIPGYTVPVVNVEVSPFTIEMSAFGYVFPK,2,Oxidation@M,23,32
335403,C(UniMod:4)SGTEASVVAPPPVVLLPDVETPSEEDC(UniMod:...,CSGTEASVVAPPPVVLLPDVETPSEEDCMFGNGK,2,Carbamidomethyl@C;Carbamidomethyl@C,1;28,34
335404,VEYELSEEGDEPQYLDLPSTATSVNIPDLLPGR2,VEYELSEEGDEPQYLDLPSTATSVNIPDLLPGR,2,,,33

In [26]:
model_mgr.predict_rt(predict_df)
model_mgr.rt_model.add_irt_column_to_precursor_df(predict_df)

2024-04-25 15:38:46> Predicting RT ...

100%|██████████| 44/44 [00:10<00:00,  4.19it/s]

Predict RT for 11 iRT precursors.
Linear regression of `rt_pred` to `irt`:
   R_square         R       slope  intercept  test_num
0   0.99007  0.995022  152.235625  -39.23216        11

,precursor_id,sequence,charge,mods,mod_sites,nAA,rt_pred,rt_norm_pred,irt_pred
0,YAVSEAAAHK3,YAVSEAAAHK,3,,,10,0.097545,0.097545,-24.382309
1,M(UniMod:35)FQEIVHK3,MFQEIVHK,3,Oxidation@M,1,8,0.192820,0.192820,-9.878066
2,LHMLELHC(UniMod:4)ESK4,LHMLELHCESK,4,Carbamidomethyl@C,8,11,0.330197,0.330197,11.035524
3,WETSFNHK3,WETSFNHK,3,,,8,0.184051,0.184051,-11.212972
4,LM(UniMod:35)NHYINK3,LMNHYINK,3,Oxidation@M,2,8,0.081633,0.081633,-26.804759
...,...,...,...,...,...,...,...,...,...
335400,SFAAGIQALGGTNINDAMLMAVQLLDSSNQEER2,SFAAGIQALGGTNINDAMLMAVQLLDSSNQEER,2,,,33,0.878060,0.878060,94.439923
335401,EC(UniMod:4)VGFEAVQEVPVGLVQPASATLYDYYNPER2,ECVGFEAVQEVPVGLVQPASATLYDYYNPER,2,Carbamidomethyl@C,2,31,0.876469,0.876469,94.197703
335402,TFQIPGYTVPVVNVEVSPFTIEM(UniMod:35)SAFGYVFPK2,TFQIPGYTVPVVNVEVSPFTIEMSAFGYVFPK,2,Oxidation@M,23,32,0.883324,0.883324,95.241198
335403,C(UniMod:4)SGTEASVVAPPPVVLLPDVETPSEEDC(UniMod:...,CSGTEASVVAPPPVVLLPDVETPSEEDCMFGNGK,2,Carbamidomethyl@C;Carbamidomethyl@C,1;28,34,0.876694,0.876694,94.231957
335404,VEYELSEEGDEPQYLDLPSTATSVNIPDLLPGR2,VEYELSEEGDEPQYLDLPSTATSVNIPDLLPGR,2,,,33,0.869372,0.869372,93.117195

In [31]:
model_mgr.predict_mobility(predict_df)

2024-04-25 15:41:48> Predicting mobility ...

100%|██████████| 44/44 [00:09<00:00,  4.48it/s]

,precursor_id,sequence,charge,mods,mod_sites,nAA,rt_pred,rt_norm_pred,irt_pred,ccs_pred,precursor_mz,mobility_pred
0,YAVSEAAAHK3,YAVSEAAAHK,3,,,10,0.097545,0.097545,-24.382309,440.278625,349.513696,0.723289
1,M(UniMod:35)FQEIVHK3,MFQEIVHK,3,Oxidation@M,1,8,0.192820,0.192820,-9.878066,437.228516,349.847910,0.718287
2,LHMLELHC(UniMod:4)ESK4,LHMLELHCESK,4,Carbamidomethyl@C,8,11,0.330197,0.330197,11.035524,576.480713,349.923249,0.712610
3,WETSFNHK3,WETSFNHK,3,,,8,0.184051,0.184051,-11.212972,418.447662,350.166408,0.687441
4,LM(UniMod:35)NHYINK3,LMNHYINK,3,Oxidation@M,2,8,0.081633,0.081633,-26.804759,434.474487,350.179660,0.713771
...,...,...,...,...,...,...,...,...,...,...,...,...
335400,SFAAGIQALGGTNINDAMLMAVQLLDSSNQEER2,SFAAGIQALGGTNINDAMLMAVQLLDSSNQEER,2,,,33,0.878060,0.878060,94.439923,612.212402,1732.842861,1.522484
335401,EC(UniMod:4)VGFEAVQEVPVGLVQPASATLYDYYNPER2,ECVGFEAVQEVPVGLVQPASATLYDYYNPER,2,Carbamidomethyl@C,2,31,0.876469,0.876469,94.197703,605.731934,1750.837570,1.506430
335402,TFQIPGYTVPVVNVEVSPFTIEM(UniMod:35)SAFGYVFPK2,TFQIPGYTVPVVNVEVSPFTIEMSAFGYVFPK,2,Oxidation@M,23,32,0.883324,0.883324,95.241198,623.428711,1790.409642,1.550577
335403,C(UniMod:4)SGTEASVVAPPPVVLLPDVETPSEEDC(UniMod:...,CSGTEASVVAPPPVVLLPDVETPSEEDCMFGNGK,2,Carbamidomethyl@C;Carbamidomethyl@C,1;28,34,0.876694,0.876694,94.231957,615.246460,1794.830770,1.530241
335404,VEYELSEEGDEPQYLDLPSTATSVNIPDLLPGR2,VEYELSEEGDEPQYLDLPSTATSVNIPDLLPGR,2,,,33,0.869372,0.869372,93.117195,630.678955,1823.885968,1.568721

In [32]:
human_atlas_library['PrecursorId'] = human_atlas_library['ModifiedPeptideSequence'] + human_atlas_library['PrecursorCharge'].astype(str)

In [38]:
human_atlas_library = human_atlas_library.set_index("PrecursorId")

In [39]:
human_atlas_library.update(
    predict_df.set_index("precursor_id")[['irt_pred', 'mobility_pred']].rename(columns={'irt_pred': 'NormalizedRetentionTime', 'mobility_pred': 'PrecursorIonMobility'})
)

In [41]:
human_atlas_library.head(25)

,PrecursorMz,ProductMz,Annotation,ProteinId,GeneName,PeptideSequence,ModifiedPeptideSequence,PrecursorCharge,LibraryIntensity,NormalizedRetentionTime,PrecursorIonMobility,FragmentType,FragmentCharge,FragmentSeriesNumber,FragmentLossType,AverageExperimentalRetentionTime
PrecursorId,,,,,,,,,,,,,,,,
YAVSEAAAHK3,349.513698,147.112805,y1^1,O75636,FCN3,YAVSEAAAHK,YAVSEAAAHK,3,2526.738037,-24.382309,0.723289,y,1,1,NaN,1225.024090
YAVSEAAAHK3,349.513698,213.626611,y4^2,O75636,FCN3,YAVSEAAAHK,YAVSEAAAHK,3,546.524048,-24.382309,0.723289,y,2,4,NaN,1225.024090
YAVSEAAAHK3,349.513698,235.107720,b2^1,O75636,FCN3,YAVSEAAAHK,YAVSEAAAHK,3,9334.356445,-24.382309,0.723289,b,1,2,NaN,1225.024090
YAVSEAAAHK3,349.513698,284.171717,y2^1,O75636,FCN3,YAVSEAAAHK,YAVSEAAAHK,3,10000.000000,-24.382309,0.723289,y,1,2,NaN,1225.024090
YAVSEAAAHK3,349.513698,334.176134,b3^1,O75636,FCN3,YAVSEAAAHK,YAVSEAAAHK,3,2099.843018,-24.382309,0.723289,b,1,3,NaN,1225.024090
YAVSEAAAHK3,349.513698,355.208831,y3^1,O75636,FCN3,YAVSEAAAHK,YAVSEAAAHK,3,5728.532715,-24.382309,0.723289,y,1,3,NaN,1225.024090
YAVSEAAAHK3,349.513698,357.182480,y7^2,O75636,FCN3,YAVSEAAAHK,YAVSEAAAHK,3,524.847107,-24.382309,0.723289,y,2,7,NaN,1225.024090
YAVSEAAAHK3,349.513698,426.245945,y4^1,O75636,FCN3,YAVSEAAAHK,YAVSEAAAHK,3,4762.276367,-24.382309,0.723289,y,1,4,NaN,1225.024090
YAVSEAAAHK3,349.513698,497.283060,y5^1,O75636,FCN3,YAVSEAAAHK,YAVSEAAAHK,3,5518.609375,-24.382309,0.723289,y,1,5,NaN,1225.024090
YAVSEAAAHK3,349.513698,626.325654,y6^1,O75636,FCN3,YAVSEAAAHK,YAVSEAAAHK,3,671.321228,-24.382309,0.723289,y,1,6,NaN,1225.024090
YAVSEAAAHK3,349.513698,713.357683,y7^1,O75636,FCN3,YAVSEAAAHK,YAVSEAAAHK,3,4404.373535,-24.382309,0.723289,y,1,7,NaN,1225.024090
M(UniMod:35)FQEIVHK3,349.847912,74.060041,y1^2,Q96KN2,CNDP1,MFQEIVHK,M(UniMod:35)FQEIVHK,3,6220.920898,-9.878066,0.718287,y,2,1,NaN,1745.524219
M(UniMod:35)FQEIVHK3,349.847912,142.589497,y2^2,Q96KN2,CNDP1,MFQEIVHK,M(UniMod:35)FQEIVHK,3,647.588806,-9.878066,0.718287,y,2,2,NaN,1745.524219
M(UniMod:35)FQEIVHK3,349.847912,147.112805,y1^1,Q96KN2,CNDP1,MFQEIVHK,M(UniMod:35)FQEIVHK,3,4729.535156,-9.878066,0.718287,y,1,1,NaN,1745.524219
M(UniMod:35)FQEIVHK3,349.847912,192.123704,y3^2,Q96KN2,CNDP1,MFQEIVHK,M(UniMod:35)FQEIVHK,3,1188.590332,-9.878066,0.718287,y,2,3,NaN,1745.524219
M(UniMod:35)FQEIVHK3,349.847912,248.665736,y4^2,Q96KN2,CNDP1,MFQEIVHK,M(UniMod:35)FQEIVHK,3,386.444305,-9.878066,0.718287,y,2,4,NaN,1745.524219
M(UniMod:35)FQEIVHK3,349.847912,284.171717,y2^1,Q96KN2,CNDP1,MFQEIVHK,M(UniMod:35)FQEIVHK,3,10000.000000,-9.878066,0.718287,y,1,2,NaN,1745.524219
M(UniMod:35)FQEIVHK3,349.847912,295.111091,b2^1,Q96KN2,CNDP1,MFQEIVHK,M(UniMod:35)FQEIVHK,3,1290.863281,-9.878066,0.718287,b,1,2,NaN,1745.524219
M(UniMod:35)FQEIVHK3,349.847912,383.240131,y3^1,Q96KN2,CNDP1,MFQEIVHK,M(UniMod:35)FQEIVHK,3,6264.470215,-9.878066,0.718287,y,1,3,NaN,1745.524219
M(UniMod:35)FQEIVHK3,349.847912,423.169669,b3^1,Q96KN2,CNDP1,MFQEIVHK,M(UniMod:35)FQEIVHK,3,1357.125000,-9.878066,0.718287,b,1,3,NaN,1745.524219
M(UniMod:35)FQEIVHK3,349.847912,496.324196,y4^1,Q96KN2,CNDP1,MFQEIVHK,M(UniMod:35)FQEIVHK,3,1310.355713,-9.878066,0.718287,y,1,4,NaN,1745.524219
M(UniMod:35)FQEIVHK3,349.847912,552.212263,b4^1,Q96KN2,CNDP1,MFQEIVHK,M(UniMod:35)FQEIVHK,3,424.148590,-9.878066,0.718287,b,1,4,NaN,1745.524219
LHMLELHC(UniMod:4)ESK4,349.923251,147.112805,y1^1,O00533,CHL1,LHMLELHCESK,LHMLELHC(UniMod:4)ESK,4,2013.635132,11.035524,0.712610,y,1,1,NaN,2181.361032
LHMLELHC(UniMod:4)ESK4,349.923251,234.144834,y2^1,O00533,CHL1,LHMLELHCESK,LHMLELHC(UniMod:4)ESK,4,2585.095215,11.035524,0.712610,y,1,2,NaN,2181.361032
LHMLELHC(UniMod:4)ESK4,349.923251,251.150253,b2^1,O00533,CHL1,LHMLELHCESK,LHMLELHC(UniMod:4)ESK,4,10000.000000,11.035524,0.712610,b,1,2,NaN,2181.361032

In [42]:
human_atlas_library.to_csv(
    "hatlas_predicted_im_rt.tsv",
    sep="\t",
    index=False
)